name: vCluster CLI Install
author: loft.sh
description: Installs the vcluster CLI
inputs:
  version:
    description: 'The version of vcluster to install'
    required: false
    default: 'latest'
  kubectl-install:
    description: 'Install kubectl if not already installed'
    required: false
    default: 'true'
  kubectl-version:
    description: 'The version of the kubectl to install'
    required: false
    default: 'latest'
runs:
  using: node20
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
